"""
Phase 9.5 — Text Typology Classification
==========================================

Rationale
---------
Every phase assumed the text encodes natural language.  The structural evidence
supports this but consistent decoding failure could mean the text has
language-LIKE properties generated by a different process.  This step tests
three alternatives without assuming the natural-language-cipher model.

Sub-analyses
------------
9.5a  Markov generation test (can a char Markov reproduce Voynich stats?)
9.5b  Glossolalia / constructed language classification
9.5c  Information density test (conditional entropy curves)
Null  Classify shuffled Voynich texts
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from voynich.core._paths import results_dir as _results_dir
from voynich.core.corpus import load_corpus
from voynich.core.reference import load_reference_corpus
from voynich.core.stats import (
    bigram_transition_matrix,
    build_ngram_lm,
    conditional_entropy,
    dtw_distance,
    entropy_curve,
    first_order_entropy,
    selectivity_ratio,
    type_token_ratio_at_n,
    word_length_distribution,
    zipf_analysis,
)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class MarkovGenerationTest:
    markov_order: int
    n_synthetic_texts: int
    voynich_stats: Dict[str, float]
    synthetic_stats: Dict[str, Dict[str, float]]  # metric -> {mean, std}
    n_metrics_within_2sigma: int
    n_metrics_total: int
    markov_sufficient: bool


@dataclass
class TypologyClassification:
    voynich_features: Dict[str, float]
    glossolalia_indicators: Dict[str, bool]
    constructed_lang_indicators: Dict[str, bool]
    natural_lang_indicators: Dict[str, bool]
    encoded_natural_indicators: Dict[str, bool]
    most_likely_type: str
    confidence: float


@dataclass
class InformationDensityTest:
    voynich_curve: Dict[int, float]
    reference_curves: Dict[str, Dict[int, float]]
    voynich_decay_rate: float
    reference_decay_rates: Dict[str, float]
    voynich_floor: float
    reference_floors: Dict[str, float]
    closest_curve_language: str
    curve_distance: float


@dataclass
class TextTypologyResult:
    markov_tests: List[Dict]
    best_markov_order: int
    best_markov_match: int
    classification: Dict
    entropy_curves: Dict
    null_shuffled_classification: str
    gate_markov: bool
    gate_classification: bool
    gate_passed: bool
    verdict: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _convert(obj: Any) -> Any:
    """Convert dataclass/numpy types to JSON-serializable form."""
    if hasattr(obj, '__dataclass_fields__'):
        return {k: _convert(v) for k, v in asdict(obj).items()}
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, dict):
        return {str(k): _convert(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_convert(item) for item in obj]
    if isinstance(obj, (bool, int, float, str, type(None))):
        return obj
    return str(obj)


def _compute_text_stats(text: str, tokens: List[str]) -> Dict[str, float]:
    """Compute the 6 key metrics for any text."""
    h1 = first_order_entropy(text)
    h2 = conditional_entropy(text, order=1)
    h3 = conditional_entropy(text, order=2)
    za = zipf_analysis(tokens)
    wld = word_length_distribution(tokens)
    ttr_vals = type_token_ratio_at_n(tokens, n_values=[len(tokens)])
    ttr = ttr_vals.get(len(tokens), len(set(tokens)) / len(tokens) if tokens else 0.0)

    # Bigram entropy
    mat, alph = bigram_transition_matrix(text)
    flat = mat.flatten()
    flat = flat[flat > 0]
    flat = flat / flat.sum() if flat.sum() > 0 else flat
    bigram_ent = -float(np.sum(flat * np.log2(flat + 1e-15))) if len(flat) > 0 else 0.0

    return {
        'h1': h1,
        'h2': h2,
        'h3': h3,
        'h2_h1_ratio': h2 / h1 if h1 > 0 else 0.0,
        'zipf_exponent': za['zipf_exponent'],
        'zipf_r_squared': za['r_squared'],
        'word_length_mean': wld.get('mean', 0.0),
        'ttr': ttr,
        'bigram_entropy': bigram_ent,
    }


def _generate_markov_text(
    source_text: str, n_chars: int, order: int = 2, seed: int = 42,
) -> str:
    """Generate synthetic text from a character-level Markov model."""
    # Build transition tables directly from text
    chars = list(source_text)
    if len(chars) <= order:
        return source_text

    transitions: Dict[tuple, List[str]] = {}
    for i in range(len(chars) - order):
        ctx = tuple(chars[i:i + order])
        nxt = chars[i + order]
        transitions.setdefault(ctx, []).append(nxt)

    rng = random.Random(seed)
    # Start from a random context
    start = rng.randint(0, len(chars) - order - 1)
    ctx = tuple(chars[start:start + order])
    result = list(ctx)

    for _ in range(n_chars - order):
        candidates = transitions.get(ctx)
        if not candidates:
            # Fall back to random context
            start = rng.randint(0, len(chars) - order - 1)
            ctx = tuple(chars[start:start + order])
            result.append(ctx[-1])
            continue
        ch = rng.choice(candidates)
        result.append(ch)
        ctx = (*ctx[1:], ch)

    return ''.join(result)


def _run_markov_test(
    voynich_text: str, voynich_tokens: List[str],
    markov_order: int, n_trials: int = 30,
) -> MarkovGenerationTest:
    """Generate Markov text and compare stats to Voynich."""
    v_stats = _compute_text_stats(voynich_text, voynich_tokens)
    n_chars = len(voynich_text)

    # Metrics to compare (excluding h1 which is trivially matched)
    compare_metrics = ['h2', 'h3', 'zipf_exponent', 'word_length_mean', 'ttr', 'bigram_entropy']

    synth_stats_all: Dict[str, List[float]] = {m: [] for m in compare_metrics}

    for trial in range(n_trials):
        synth_text = _generate_markov_text(
            voynich_text, n_chars, order=markov_order, seed=42 + trial,
        )
        synth_tokens = synth_text.split()
        if len(synth_tokens) < 50:
            continue
        ss = _compute_text_stats(synth_text, synth_tokens)
        for m in compare_metrics:
            synth_stats_all[m].append(ss[m])

    # Compare: how many metrics are within 2 sigma?
    synth_summary: Dict[str, Dict[str, float]] = {}
    n_within = 0
    for m in compare_metrics:
        vals = synth_stats_all[m]
        if not vals:
            synth_summary[m] = {'mean': 0.0, 'std': 0.0}
            continue
        mean = float(np.mean(vals))
        std = float(np.std(vals))
        synth_summary[m] = {'mean': mean, 'std': std}
        if std > 0 and abs(v_stats[m] - mean) < 2 * std:
            n_within += 1
        elif std == 0 and abs(v_stats[m] - mean) < 0.01:
            n_within += 1

    return MarkovGenerationTest(
        markov_order=markov_order,
        n_synthetic_texts=n_trials,
        voynich_stats=v_stats,
        synthetic_stats=synth_summary,
        n_metrics_within_2sigma=n_within,
        n_metrics_total=len(compare_metrics),
        markov_sufficient=n_within >= 5,
    )


def _classify_text(features: Dict[str, float]) -> TypologyClassification:
    """Rule-based text type classification from statistical features."""
    h2_h1 = features.get('h2_h1_ratio', 0.0)
    ttr = features.get('ttr', 0.0)
    h3 = features.get('h3', 0.0)
    zipf_r2 = features.get('zipf_r_squared', 0.0)
    zipf_exp = features.get('zipf_exponent', 0.0)

    glossolalia = {
        'high_h2_h1_ratio': h2_h1 > 0.8,
        'low_ttr': ttr < 0.15,
        'very_low_h3': h3 < 0.5,
    }

    constructed = {
        'moderate_h2_h1_ratio': 0.4 <= h2_h1 <= 0.7,
        'zipfian': zipf_r2 > 0.9,
        'regular_exponent': 0.8 <= zipf_exp <= 1.2,
    }

    natural = {
        'natural_h2_h1_ratio': 0.3 <= h2_h1 <= 0.6,
        'zipfian': zipf_r2 > 0.85,
        'normal_ttr': 0.1 <= ttr <= 0.5,
    }

    encoded_natural = {
        'anomalous_h2_h1': h2_h1 < 0.3 or h2_h1 > 0.6,
        'zipfian': zipf_r2 > 0.85,
        'normal_ttr': 0.1 <= ttr <= 0.5,
    }

    # Score each type
    scores = {
        'glossolalia': sum(glossolalia.values()) / len(glossolalia),
        'constructed': sum(constructed.values()) / len(constructed),
        'natural': sum(natural.values()) / len(natural),
        'encoded_natural': sum(encoded_natural.values()) / len(encoded_natural),
    }

    best_type = max(scores, key=scores.get)
    confidence = scores[best_type]

    return TypologyClassification(
        voynich_features=features,
        glossolalia_indicators=glossolalia,
        constructed_lang_indicators=constructed,
        natural_lang_indicators=natural,
        encoded_natural_indicators=encoded_natural,
        most_likely_type=best_type,
        confidence=confidence,
    )


def _entropy_decay_rate(curve: Dict[int, float]) -> float:
    """Linear regression slope on entropy curve (order vs entropy)."""
    orders = sorted(curve.keys())
    if len(orders) < 2:
        return 0.0
    x = np.array(orders, dtype=float)
    y = np.array([curve[o] for o in orders], dtype=float)
    A = np.vstack([x, np.ones(len(x))]).T
    try:
        slope, _ = np.linalg.lstsq(A, y, rcond=None)[0]
    except np.linalg.LinAlgError:
        slope = 0.0
    return float(slope)


# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def run_text_typology() -> Dict:
    """
    Phase 9.5: Classify the Voynich text by typology — natural language,
    cipher, constructed language, or glossolalia.
    """
    print("Phase 9.5: Text Typology Classification")
    print("=" * 60)

    # --- Load data ---
    corpus = load_corpus(verbose=False)
    ref_corpus = load_reference_corpus(verbose=False)
    voynich_tokens = corpus.get_tokens(language='A')
    voynich_text = corpus.get_text(language='A')
    print(f"  Voynich Language A: {len(voynich_tokens):,} tokens, "
          f"{len(voynich_text):,} characters")

    # ===================================================================
    # 9.5a: Markov generation test
    # ===================================================================
    print("\n  9.5a: Markov generation test ...")
    markov_tests: List[MarkovGenerationTest] = []
    best_order = 1
    best_match = 0

    for order in (1, 2, 3):
        print(f"    Order {order} ...")
        mt = _run_markov_test(voynich_text, voynich_tokens, order, n_trials=30)
        markov_tests.append(mt)
        print(f"      Metrics within 2 sigma: {mt.n_metrics_within_2sigma}/{mt.n_metrics_total}")
        print(f"      Markov sufficient: {mt.markov_sufficient}")
        if mt.n_metrics_within_2sigma > best_match:
            best_match = mt.n_metrics_within_2sigma
            best_order = order

    print(f"    Best Markov order: {best_order} "
          f"({best_match}/{markov_tests[0].n_metrics_total} metrics)")

    # ===================================================================
    # 9.5b: Text type classification
    # ===================================================================
    print("\n  9.5b: Text type classification ...")
    v_features = _compute_text_stats(voynich_text, voynich_tokens)
    classification = _classify_text(v_features)

    print(f"    H2/H1 ratio: {v_features['h2_h1_ratio']:.3f}")
    print(f"    TTR: {v_features['ttr']:.4f}")
    print(f"    Zipf R²: {v_features['zipf_r_squared']:.4f}")
    print(f"    Classification: {classification.most_likely_type} "
          f"(confidence={classification.confidence:.2f})")
    print(f"    Glossolalia indicators: {classification.glossolalia_indicators}")
    print(f"    Constructed indicators: {classification.constructed_lang_indicators}")
    print(f"    Natural indicators: {classification.natural_lang_indicators}")
    print(f"    Encoded natural indicators: {classification.encoded_natural_indicators}")

    # ===================================================================
    # 9.5c: Information density / entropy curves
    # ===================================================================
    print("\n  9.5c: Information density (entropy curves) ...")
    max_order = 6  # Keep manageable for computation time

    v_curve = entropy_curve(voynich_text, max_order=max_order)
    print(f"    Voynich entropy curve: "
          + "  ".join(f"H{k}={v:.3f}" for k, v in sorted(v_curve.items())))

    ref_curves: Dict[str, Dict[int, float]] = {}
    for lang in ('latin', 'occitan', 'italian', 'german'):
        try:
            ref_text = ref_corpus.get_combined_text(lang)
            if len(ref_text) < 200:
                continue
            # Subsample to Voynich size for fair comparison
            ref_text = ref_text[:len(voynich_text)]
            rc = entropy_curve(ref_text, max_order=max_order)
            ref_curves[lang] = rc
            print(f"    {lang}: "
                  + "  ".join(f"H{k}={v:.3f}" for k, v in sorted(rc.items())))
        except Exception as e:
            print(f"    {lang}: failed — {e}")

    # Decay rates and floors
    v_decay = _entropy_decay_rate(v_curve)
    v_floor = v_curve.get(max_order, 0.0)
    ref_decays = {lang: _entropy_decay_rate(c) for lang, c in ref_curves.items()}
    ref_floors = {lang: c.get(max_order, 0.0) for lang, c in ref_curves.items()}

    print(f"    Voynich decay rate: {v_decay:.4f}  floor: {v_floor:.3f}")
    for lang in ref_decays:
        print(f"    {lang} decay rate: {ref_decays[lang]:.4f}  floor: {ref_floors[lang]:.3f}")

    # Find closest curve via DTW
    closest_lang = 'none'
    closest_dist = float('inf')
    v_seq = [v_curve[k] for k in sorted(v_curve.keys())]
    for lang, rc in ref_curves.items():
        r_seq = [rc[k] for k in sorted(rc.keys())]
        dist = dtw_distance(v_seq, r_seq)
        if dist < closest_dist:
            closest_dist = dist
            closest_lang = lang
    print(f"    Closest entropy curve: {closest_lang} (DTW={closest_dist:.4f})")

    info_density = InformationDensityTest(
        voynich_curve={int(k): v for k, v in v_curve.items()},
        reference_curves={lang: {int(k): v for k, v in c.items()}
                          for lang, c in ref_curves.items()},
        voynich_decay_rate=v_decay,
        reference_decay_rates=ref_decays,
        voynich_floor=v_floor,
        reference_floors=ref_floors,
        closest_curve_language=closest_lang,
        curve_distance=closest_dist,
    )

    # ===================================================================
    # Null test: classify shuffled Voynich
    # ===================================================================
    print("\n  Null test: shuffled Voynich classification ...")
    rng = random.Random(42)
    shuffled_tokens = voynich_tokens.copy()
    rng.shuffle(shuffled_tokens)
    shuffled_text = ' '.join(shuffled_tokens)
    shuffled_features = _compute_text_stats(shuffled_text, shuffled_tokens)
    shuffled_class = _classify_text(shuffled_features)
    print(f"    Word-shuffled classification: {shuffled_class.most_likely_type} "
          f"(confidence={shuffled_class.confidence:.2f})")

    # ===================================================================
    # Gate
    # ===================================================================
    gate_markov = best_match >= 5  # Markov reproduces >= 5/6 metrics
    gate_classification = classification.confidence >= 0.7
    gate_passed = gate_markov or gate_classification

    if gate_markov and classification.most_likely_type in ('glossolalia', 'constructed'):
        verdict = 'structure_is_low_order_not_linguistic'
    elif gate_markov and classification.most_likely_type in ('natural', 'encoded_natural'):
        verdict = 'markov_matches_but_classification_says_natural'
    elif gate_classification:
        verdict = f'classified_as_{classification.most_likely_type}'
    elif not gate_markov and not gate_classification:
        verdict = 'ambiguous_typology'
    else:
        verdict = 'inconclusive'

    print(f"\n  Gate: markov={gate_markov}  "
          f"classification={gate_classification}  passed={gate_passed}")
    print(f"  Verdict: {verdict}")

    # ===================================================================
    # Save
    # ===================================================================
    result = TextTypologyResult(
        markov_tests=[_convert(asdict(mt)) for mt in markov_tests],
        best_markov_order=best_order,
        best_markov_match=best_match,
        classification=_convert(asdict(classification)),
        entropy_curves=_convert(asdict(info_density)),
        null_shuffled_classification=shuffled_class.most_likely_type,
        gate_markov=gate_markov,
        gate_classification=gate_classification,
        gate_passed=gate_passed,
        verdict=verdict,
    )

    out = _convert(asdict(result))
    with open(_results_dir() / 'text_typology.json', 'w') as f:
        json.dump(out, f, indent=2)

    print(f"\n  Results saved to results/text_typology.json")
    return out
